default:
    image: docker:19.03
    retry: 1

stages:
    - build

build chromedriver:
    stage: build
    variables:
        BUILDX_VERSION: 0.5.1
    before_script:
        - apk add --no-cache curl
        - mkdir -p /usr/lib/docker/cli-plugins
        - curl -L --output /usr/lib/docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64"
        - chmod a+x /usr/lib/docker/cli-plugins/docker-buildx
        - docker buildx create --use

    script:
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
        - docker buildx build -t ${CI_REGISTRY_IMAGE} --push .

    after_script:
        - docker buildx rm
