default:
    image: docker:stable
    retry: 1

stages:
    - build

build chromedriver:
    stage: build
    services:
        - name: tonistiigi/binfmt
          command:
              - --install
              - all
        - name: moby/buildkit:latest
          alias: buildkitd
          command:
              - --addr
              - tcp://0.0.0.0:1234
    variables:
        BUILDX_VERSION: 0.9.1
    before_script:
        - apk add --no-cache curl
        - mkdir -p /usr/lib/docker/cli-plugins
        - curl -L --output /usr/lib/docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64"
        - chmod a+x /usr/lib/docker/cli-plugins/docker-buildx
        - docker buildx create --use --driver remote tcp://buildkitd:1234

    script:
        - |   # docker login without docker engine
            BASE64_AUTH=$(echo -n "gitlab-ci-token:${CI_JOB_TOKEN}" | base64)
            mkdir -p ~/.docker
            echo "{\"auths\": {\"${CI_REGISTRY}\": {\"auth\": \"${BASE64_AUTH}\"}}}" > ~/.docker/config.json

        - docker buildx build
            --platform linux/arm64/v8,linux/amd64
            --tag ${CI_REGISTRY_IMAGE}:bullseye --push .
